# Generated by Django 4.1.4 on 2023-01-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, null=True)),
                ("dob", models.DateField(null=True)),
                ("address_line_1", models.CharField(max_length=100, null=True)),
                ("address_line_2", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
                ("zip_code", models.CharField(max_length=10, null=True)),
                ("county", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customer",
                "ordering": ["-user__date_joined", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, null=True)),
                ("price", models.FloatField(null=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                    ),
                ),
                ("product", models.ManyToManyField(null=True, to="core.product")),
            ],
            options={
                "db_table": "order",
                "ordering": ["-date_created"],
            },
        ),
    ]
