# Generated by Django 4.1.4 on 2023-01-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="core.product"),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.album",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("album", "order")},
            },
        ),
    ]
